### ISSUE TITLE
Allow configuring preload crossorigin

### ISSUE THREAD

**Issue by LarsDenBakker** [vikerman/rollup-plugin-hoist-import-deps#12]
Safari has a bug where cross origin anonymous doesn't send along credentials on the same origin: https://bugs.webkit.org/show_bug.cgi?id=171566

I need certain cookies when fetching JS resources. Could you add an option to not set any cross origin attribute at all for the preload?

**Comment by vikerman** [comment]
Offline discussion -

"When do we actually need crossorigin attribute? Can we just remove it?"

"I think es modules are fetched with crossorigin anonymous, and you need credentials to match to hit the cache
In my case im compiling to systemjs, which uses script tags
Its not a problem if you don't actually use cookies for js files, then the current default works for all."
